### ISSUE TITLE
ShuffleWriteTime values

### ISSUE THREAD

**Issue by Brandonage** [hammerlab/slim#43]
Hello:

I'm not sure about the meaning of the ShuffleWriteTime field that its written in the task_attempts collection 

![image](https://cloud.githubusercontent.com/assets/12024997/15501437/c03e0e96-21ad-11e6-8a74-c3cd72d6218e.png)

It says 2590421 but the task only lasts for 13830 ms. How is this possible?. It's some kind of aggregate value over the stage?

Thanks in advance

**Comment by ryan-williams** [comment]
Hi there, sorry for the delay, I think [these lines in Spark](https://github.com/apache/spark/blob/v1.6.1/core/src/main/scala/org/apache/spark/executor/TaskMetrics.scala#L421-L427) are relevant:

> Time the task spent blocking on writes to disk or buffer cache, **in nanoseconds**

So in your example it was 2.59ms of shuffle-write.
